version: '3'

services:
  db_mysql:
    image: mysql:8.0-oracle
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3306:3306"
  
  db_postgresql:
    container_name: postgres_container
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"